export const theme = {
  colors: {
    google: {
      blue: '#4285F4',
      red: '#EA4335',
      yellow: '#FBBC05',
      green: '#34A853',
      greenLight: '#5DB975',
    },
    background: {
      light: 'bg-white',
      dark: 'dark:bg-[#1a1a1a]',
      sidebar: 'bg-gray-50 dark:bg-[#121212]',
    },
  },
  components: {
    layout: {
      screen: 'min-h-screen flex flex-col md:flex-row bg-white dark:bg-[#121212] text-gray-600 dark:text-gray-300',
      header: 'md:hidden flex items-center justify-between p-4 border-b border-gray-300 dark:border-gray-700 bg-white dark:bg-[#121212] sticky top-0 z-40',
      mobileMenu: 'md:hidden fixed inset-x-0 top-[65px] bg-white dark:bg-[#121212] border-b border-gray-300 dark:border-gray-700 shadow-xl z-30 animate-in slide-in-from-top duration-200 overflow-y-auto max-h-[calc(100vh-65px)]',
    },
    modal: {
      overlay: 'fixed inset-0 bg-black/80 backdrop-blur-md flex items-center justify-center p-4 z-[100] animate-in fade-in duration-300',
      container: 'bg-white dark:bg-[#121212] w-full max-w-md rounded-[2.5rem] border-4 p-8 animate-in zoom-in-95 duration-200 text-center',
      containerBlue: 'border-google-blue shadow-[0_0_50px_rgba(66,133,244,0.3)]',
      containerRed: 'border-google-red shadow-[0_0_50px_rgba(234,67,53,0.3)]',
      iconContainer: 'w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-6 ring-8',
      iconContainerBlue: 'bg-blue-50 dark:bg-blue-900/30 ring-blue-50 dark:ring-blue-900/10 text-google-blue',
      iconContainerRed: 'bg-red-50 dark:bg-red-900/30 ring-red-50 dark:ring-red-900/10 text-google-red',
      infoBox: 'p-4 rounded-2xl border-2 mb-8',
      infoBoxBlue: 'bg-blue-50 dark:bg-blue-900/20 border-blue-100 dark:border-blue-900/30 text-google-blue',
      infoBoxRed: 'bg-red-50 dark:bg-red-900/20 border-red-100 dark:border-red-900/30 text-google-red',
      title: 'text-2xl font-black text-gray-900 dark:text-gray-300 mb-4 uppercase tracking-tight',
      message: 'text-sm font-black uppercase leading-relaxed',
      buttonPrimary: 'w-full h-14 rounded-2xl font-black uppercase tracking-widest shadow-lg text-white',
      buttonSecondary: 'w-full h-14 rounded-2xl font-black uppercase tracking-widest border-2 border-gray-200 dark:border-gray-700',
    },
    dangerModal: {
      overlay: 'fixed inset-0 bg-black/90 backdrop-blur-xl flex items-center justify-center p-4 z-[110] animate-in fade-in duration-300',
      container: 'bg-white dark:bg-[#121212] w-full max-w-md rounded-[2.5rem] border-[6px] border-google-red p-8 shadow-[0_0_100px_rgba(234,67,53,0.5)] animate-in zoom-in-95 duration-200 text-center',
      iconContainer: 'w-24 h-24 bg-red-600 rounded-full flex items-center justify-center mx-auto mb-6 animate-bounce shadow-2xl',
      title: 'text-3xl font-black text-red-600 dark:text-red-500 mb-4 uppercase tracking-tighter',
      infoBox: 'p-6 bg-red-600/10 dark:bg-red-900/40 rounded-2xl border-2 border-red-600 mb-8',
      message: 'text-lg font-black text-red-600 dark:text-red-400 uppercase leading-tight',
      buttonPrimary: 'w-full h-16 rounded-2xl font-black uppercase tracking-widest bg-red-600 hover:bg-red-700 text-white shadow-2xl',
      buttonSecondary: 'w-full h-14 rounded-2xl font-black uppercase tracking-widest bg-google-green border-google-green text-white shadow-lg',
    },
    generalModal: {
      overlay: 'fixed inset-0 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4 z-50',
      container: 'bg-white dark:bg-[#121212] w-full max-w-md rounded-3xl p-8 border border-gray-300 dark:border-gray-700 animate-in zoom-in-95 duration-200 shadow-2xl',
      header: 'flex items-center justify-between mb-8',
      title: 'text-xl font-black uppercase tracking-widest',
    },
    dashboard: {
      container: 'bg-blue-100/70 dark:bg-blue-900/10 rounded-container border border-blue-200 dark:border-gray-800 mb-8 shadow-sm overflow-hidden',
      header: 'flex flex-col sm:flex-row sm:items-center justify-between p-6 cursor-pointer hover:bg-blue-100/60 dark:hover:bg-blue-900/20 transition-colors gap-4',
      sectionCard: 'space-y-4 border border-blue-200 dark:border-gray-800 rounded-card p-6 shadow-sm bg-white/80 dark:bg-transparent',
      headerIdentification: 'text-[10px] font-black uppercase text-google-blue tracking-widest border-b border-gray-100 dark:border-gray-800 pb-2 mb-4',
      headerPlanning: 'text-[10px] font-black uppercase text-google-green tracking-widest border-b border-gray-100 dark:border-gray-800 pb-2 mb-4',
      headerBuilding: 'text-[10px] font-black uppercase text-orange-500 tracking-widest border-b border-gray-100 dark:border-gray-800 pb-2 mb-4',
      label: 'text-[10px] font-black uppercase text-gray-500 dark:text-gray-400 tracking-wider mb-1',
      consultantCard: 'bg-white/80 dark:bg-black/40 rounded-container border border-blue-200 dark:border-gray-800 p-6 shadow-sm hover:border-google-blue transition-all group/card',
    },
    taskDoneButton: {
      base: 'flex-1 h-12 rounded-xl font-black uppercase tracking-[0.15em] text-xs flex items-center justify-center gap-2 transition-all duration-300 shadow-[0_10px_25px_rgba(0,0,0,0.3)] active:scale-95 active:shadow-inner border',
      active: 'bg-google-green-light text-white border-white/20 hover:animate-pulse-gold',
      completed: 'bg-white text-google-green border-white animate-pulse',
      multiUser: 'bg-google-red text-white border-white/30 hover:animate-pulse-gold',
      multiUserCompleted: 'bg-white text-google-red border-white',
      yellowState: 'bg-google-yellow text-gray-900 border-white/30 hover:animate-pulse-gold',
      yellowStateCompleted: 'bg-white text-google-yellow border-white animate-pulse',
    },
    sidebar: {
      shell: 'border-gray-300 dark:border-gray-700 bg-gray-50 dark:bg-black/60 flex flex-col shadow-2xl z-40 fixed md:relative right-0 top-[65px] md:top-0 h-[calc(100vh-65px)] md:h-screen transition-all duration-500 ease-[cubic-bezier(0.4,0,0.2,1)] overflow-hidden',
      header: 'p-6 border-b border-google-blue/30 flex items-center justify-between bg-google-blue text-white shadow-lg cursor-pointer hover:bg-google-blue/90 transition-colors group/sidebar-header',
      emptyState: 'flex flex-col items-center justify-center py-20 text-center px-6',
      emptyIcon: 'w-16 h-16 rounded-full bg-gray-100 dark:bg-white/5 flex items-center justify-center text-gray-300 dark:text-gray-700 mb-4',
      emptyText: 'text-[10px] font-black uppercase text-gray-500 tracking-widest leading-relaxed',
      activeTask: 'group rounded-card border-2 cursor-pointer relative flex flex-col transition-all',
      activeTaskMulti: 'bg-google-red border-google-red text-white shadow-2xl scale-[1.05] z-20 animate-pulse',
      activeTaskFocus: 'bg-google-green border-google-green text-white shadow-lg scale-[1.02] z-10',
      activeTaskYellow: 'bg-google-yellow border-google-yellow text-gray-900 shadow-lg scale-[1.02] z-10',
      inactiveTask: 'bg-google-blue/5 dark:bg-google-blue/10 border-google-blue dark:border-google-blue hover:border-google-blue min-h-[64px]',
      deactivatedCompleted: 'bg-google-green/10 border-google-green/20 text-google-green dark:text-google-green/80 shadow-sm min-h-[64px]',
    },
    checklist: {
      container: 'flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-3 py-2 sm:py-2.5 px-3 sm:px-4 rounded-card group transition-all border shadow-sm hover:shadow-md cursor-pointer relative',
      containerActive: 'bg-gray-100 border-google-green dark:bg-black/60 dark:border-google-green ring-4 ring-google-green/30 shadow-lg',
      containerMulti: 'bg-google-red border-google-red text-white shadow-2xl scale-[1.02] z-20 animate-pulse',
      containerInactive: 'bg-white border-blue-200 hover:bg-blue-50/50 dark:hover:bg-blue-900/10 dark:border-gray-800',
      badge: 'text-[8px] font-black uppercase px-1.5 py-0.5 rounded-md border transition-all',
      badgeActive: 'bg-google-yellow border-google-yellow text-gray-900 shadow-sm',
      badgeInactive: 'bg-gray-100 dark:bg-white/10 text-gray-500 dark:text-gray-300 border-gray-200 dark:border-white/10',
    },
    pomodoro: {
      container: 'flex-1 h-10 flex items-center justify-center px-1.5 py-1 rounded-xl transition-all shadow-sm min-w-0 bg-white/10',
      button: 'w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0 transition-all shadow-sm bg-white/20 border-white/30 text-white',
      buttonYellow: 'bg-black/10 border-black/20 text-gray-900',
    },
  },
  animations: {
    pulseGold: 'animate-pulse-gold',
  }
};
