export const theme = {
  colors: {
    google: {
      blue: 'var(--brand-blue)',
      red: 'var(--brand-red)',
      yellow: 'var(--brand-yellow)',
      green: 'var(--brand-green)',
      greenLight: 'var(--brand-green-light)',
    },
    background: {
      light: 'bg-app-bg',
      dark: 'dark:bg-app-bg',
      sidebar: 'bg-sidebar-bg',
      console: 'bg-console-bg',
    },
    text: {
      primary: 'text-text-primary',
      secondary: 'text-text-secondary',
      heading: 'text-text-heading',
    }
  },
  components: {
    layout: {
      screen: 'min-h-screen flex flex-col md:flex-row bg-app-bg text-text-primary',
      header: 'md:hidden flex items-center justify-between p-4 border-b border-gray-300 dark:border-gray-700 bg-app-bg sticky top-0 z-40',
      mobileMenu: 'md:hidden fixed inset-x-0 top-[65px] bg-app-bg border-b border-gray-300 dark:border-gray-700 shadow-xl z-30 animate-in slide-in-from-top duration-200 overflow-y-auto max-h-[calc(100vh-65px)]',
      desktopSidebar: 'hidden md:flex w-64 border-r border-gray-300 dark:border-gray-700 p-4 md:pt-8 md:px-4 md:pb-4 flex flex-col gap-6 bg-sidebar-bg',
      mainContent: 'flex-1 p-4 md:p-8 overflow-y-auto flex flex-col',
      contentHeader: 'w-full px-0 sm:px-4 md:px-12 flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8',
    },
    nav: {
      item: 'flex items-center gap-3 px-3 py-2 rounded-lg transition-colors',
      itemActive: 'bg-blue-50 text-google-blue dark:bg-blue-900/20',
      itemInactive: 'hover:bg-gray-100 dark:hover:bg-gray-800',
      pill: 'px-4 py-2 rounded-full border-2 transition-all font-bold text-left',
      pillActiveBlue: 'bg-google-blue border-google-blue text-white shadow-md',
      pillActiveGreen: 'bg-google-green border-google-green text-white shadow-md',
      pillInactive: 'border-gray-300 dark:border-gray-700 hover:border-google-blue text-gray-800 dark:text-gray-300',
    },
    profile: {
      card: 'flex items-center gap-3 px-3 py-2 bg-gray-100 dark:bg-black/40 rounded-card border border-gray-200 dark:border-gray-700 mb-2',
      avatar: 'w-9 h-9 rounded-full bg-google-blue/10 flex items-center justify-center text-google-blue flex-shrink-0',
    },
    modal: {
      overlay: 'fixed inset-0 bg-black/80 backdrop-blur-md flex items-center justify-center p-4 z-[100] animate-in fade-in duration-300',
      container: 'bg-white dark:bg-[#121212] w-full max-w-md rounded-[2.5rem] border-4 p-8 animate-in zoom-in-95 duration-200 text-center',
      containerBlue: 'border-google-blue shadow-[0_0_50px_rgba(66,133,244,0.3)]',
      containerRed: 'border-google-red shadow-[0_0_50px_rgba(234,67,53,0.3)]',
      iconContainer: 'w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-6 ring-8',
      iconContainerBlue: 'bg-blue-50 dark:bg-blue-900/30 ring-blue-50 dark:ring-blue-900/10 text-google-blue',
      iconContainerRed: 'bg-red-50 dark:bg-red-900/30 ring-red-50 dark:ring-red-900/10 text-google-red',
      infoBox: 'p-4 rounded-2xl border-2 mb-8',
      infoBoxBlue: 'bg-blue-50 dark:bg-blue-900/20 border-blue-100 dark:border-blue-900/30 text-google-blue',
      infoBoxRed: 'bg-red-50 dark:bg-red-900/20 border-red-100 dark:border-red-900/30 text-google-red',
      title: 'text-2xl font-black text-gray-900 dark:text-gray-300 mb-4 uppercase tracking-tight',
      message: 'text-sm font-black uppercase leading-relaxed',
      buttonPrimary: 'w-full h-14 rounded-2xl font-black uppercase tracking-widest shadow-lg text-white',
      buttonSecondary: 'w-full h-14 rounded-2xl font-black uppercase tracking-widest border-2 border-gray-200 dark:border-gray-700',
    },
    dangerModal: {
      overlay: 'fixed inset-0 bg-black/90 backdrop-blur-xl flex items-center justify-center p-4 z-[110] animate-in fade-in duration-300',
      container: 'bg-white dark:bg-[#121212] w-full max-w-md rounded-[2.5rem] border-[6px] border-google-red p-8 shadow-[0_0_100px_rgba(234,67,53,0.5)] animate-in zoom-in-95 duration-200 text-center',
      iconContainer: 'w-24 h-24 bg-red-600 rounded-full flex items-center justify-center mx-auto mb-6 animate-bounce shadow-2xl',
      title: 'text-3xl font-black text-red-600 dark:text-red-500 mb-4 uppercase tracking-tighter',
      infoBox: 'p-6 bg-red-600/10 dark:bg-red-900/40 rounded-2xl border-2 border-red-600 mb-8',
      message: 'text-lg font-black text-red-600 dark:text-red-400 uppercase leading-tight',
      buttonPrimary: 'w-full h-16 rounded-2xl font-black uppercase tracking-widest bg-red-600 hover:bg-red-700 text-white shadow-2xl',
      buttonSecondary: 'w-full h-14 rounded-2xl font-black uppercase tracking-widest bg-google-green border-google-green text-white shadow-lg',
    },
    generalModal: {
      overlay: 'fixed inset-0 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4 z-50',
      container: 'bg-white dark:bg-[#121212] w-full max-w-md rounded-3xl p-8 border border-gray-300 dark:border-gray-700 animate-in zoom-in-95 duration-200 shadow-2xl',
      header: 'flex items-center justify-between mb-8',
      title: 'text-xl font-black uppercase tracking-widest',
    },
    dashboard: {
      projectInfoContainer: 'bg-[var(--project-info-bg)] dark:bg-blue-900/10 rounded-container border border-[var(--project-info-border)] dark:border-gray-800 mb-8 shadow-sm overflow-hidden',
      header: 'flex flex-col sm:flex-row sm:items-center justify-between p-6 cursor-pointer hover:bg-blue-100/60 dark:hover:bg-blue-900/20 transition-colors gap-4',
      sectionCard: 'space-y-4 border border-[var(--metadata-card-border)] dark:border-gray-800 rounded-card p-6 shadow-sm bg-[var(--metadata-card-bg)] dark:bg-transparent',
      headerIdentification: 'text-[10px] font-black uppercase text-[var(--section-ident)] tracking-widest border-b border-gray-100 dark:border-gray-800 pb-2 mb-4',
      headerPlanning: 'text-[10px] font-black uppercase text-[var(--section-plan)] tracking-widest border-b border-gray-100 dark:border-gray-800 pb-2 mb-4',
      headerBuilding: 'text-[10px] font-black uppercase text-[var(--section-build)] tracking-widest border-b border-gray-100 dark:border-gray-800 pb-2 mb-4',
      iconIdent: 'text-[var(--section-ident-icon)]',
      iconPlan: 'text-[var(--section-plan-icon)]',
      iconBuild: 'text-[var(--section-build-icon)]',
      label: 'text-[10px] font-black uppercase text-gray-500 dark:text-gray-400 tracking-wider mb-1',
      consultantCard: 'bg-[var(--metadata-card-bg)] dark:bg-black/40 rounded-container border border-[var(--metadata-card-border)] dark:border-gray-800 p-6 shadow-sm hover:border-google-blue transition-all group/card',
      checklistContainer: 'bg-[var(--checklist-bg)] dark:bg-blue-900/10 rounded-[2.5rem] p-4 md:p-12 border border-[var(--checklist-border)] dark:border-gray-800 shadow-sm',
    },
    hierarchy: {
      section: 'flex items-center gap-2 sm:gap-3 group mb-2 bg-white/60 dark:bg-black/40 p-1 sm:pl-1.5 sm:pr-5 rounded-card border border-blue-200 dark:border-gray-800 transition-all hover:shadow-md',
      sectionTitle: 'text-lg sm:text-xl font-heading tracking-heading text-text-heading',
      verticalLine: 'absolute bg-[var(--hierarchy-line)] pointer-events-none transition-[height,top] duration-150',
      innerContainer: 'ml-0.5 sm:ml-4 relative pl-2 sm:pl-6 py-2',
      subsection: 'my-1 sm:my-2 bg-white/60 dark:bg-black/40 rounded-card border border-blue-200 dark:border-gray-800 p-1 sm:pl-1.5 sm:pr-5 transition-all hover:shadow-md relative group/sub',
      subsectionTitle: 'font-heading tracking-heading text-text-primary text-sm sm:text-lg break-words whitespace-pre-wrap min-w-0 transition-all duration-300',
      horizontalLine: 'absolute -left-[0.5rem] sm:-left-[1.5rem] top-5 sm:top-6 w-[0.5rem] sm:w-[1.5rem] h-[1px] bg-[var(--hierarchy-line)]',
      addTaskButton: 'flex group/add-task text-[10px] sm:text-xs text-text-secondary font-heading ml-2 sm:ml-4 py-1.5 px-2 sm:px-3 transition-all items-center gap-2 rounded-button hover:bg-white dark:hover:bg-gray-800 shadow-xs border border-transparent hover:border-gray-200 dark:hover:border-gray-700',
      addSubsectionButton: 'text-xs sm:text-sm font-heading text-text-secondary hover:text-google-blue flex items-center gap-2 transition-all py-2.5 px-4 rounded-button bg-transparent border-dashed border-2 border-gray-300 dark:border-gray-700 hover:border-google-blue hover:bg-blue-50/50 dark:hover:bg-blue-900/20 relative z-20',
    },
    taskGuide: {
      block: 'bg-white dark:bg-black/40 border border-gray-400 dark:border-gray-700 rounded-container p-6 shadow-sm',
      blockPrereq: 'rounded-container border-2 p-6 transition-all shadow-sm',
      blockPrereqActive: 'border-orange-200 bg-orange-100 dark:border-orange-500/50 dark:bg-orange-500/10',
      header: 'text-[10px] font-black uppercase text-gray-600 dark:text-gray-300/70 tracking-[0.2em] mb-3 block px-2',
      headerPrereq: 'flex items-center gap-2 text-orange-600 dark:text-orange-400 mb-4 px-2',
      inputMaster: 'w-full bg-blue-50/30 dark:bg-gray-900 border-2 border-gray-200 dark:border-gray-700 rounded-card p-4 text-sm font-medium focus:border-google-blue outline-none transition-colors text-gray-800 dark:text-gray-100 resize-y min-h-[6rem] placeholder-gray-400',
      itemPrereq: 'flex items-center justify-between bg-white dark:bg-black/40 px-4 py-3 rounded-card border border-orange-100 dark:border-orange-500/20 shadow-sm group',
      itemPrep: 'flex flex-col bg-blue-50/20 dark:bg-black/40 p-4 rounded-card border border-blue-100 dark:border-gray-800 shadow-sm group',
    },
    docExplorer: {
      overlay: 'fixed inset-0 bg-black/70 backdrop-blur-sm z-[100] flex items-center justify-center p-4',
      shell: 'bg-white dark:bg-[#121212] w-full max-w-5xl h-[80vh] rounded-container border border-gray-300 dark:border-gray-700 shadow-2xl flex flex-col overflow-hidden',
      header: 'p-6 border-b border-gray-100 dark:border-gray-800 flex items-center justify-between bg-gray-50/50 dark:bg-black/20',
      toolbar: 'p-4 border-b border-gray-100 dark:border-gray-800 flex flex-col gap-4',
      grid: 'grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-6',
      card: 'group relative bg-white dark:bg-black/40 border-2 border-transparent hover:border-google-blue rounded-2xl p-4 shadow-sm transition-all cursor-pointer',
      table: 'w-full text-left',
      tableHeader: 'bg-gray-50/50 dark:bg-black/60 border-b border-gray-100 dark:border-gray-800',
      tableRow: 'hover:bg-gray-50 dark:hover:bg-white/5 cursor-pointer transition-colors group',
    },
    taskDoneButton: {
      base: 'flex-1 h-12 rounded-xl font-black uppercase tracking-[0.15em] text-xs flex items-center justify-center gap-2 transition-all duration-300 shadow-[0_10px_25px_rgba(0,0,0,0.3)] active:scale-95 active:shadow-inner border',
      active: 'bg-google-green-light text-white border-white/20 hover:animate-pulse-gold',
      completed: 'bg-white text-google-green border-white animate-pulse',
      multiUser: 'bg-google-red text-white border-white/30 hover:animate-pulse-gold',
      multiUserCompleted: 'bg-white text-google-red border-white',
      yellowState: 'bg-google-yellow text-gray-900 border-white/30 hover:animate-pulse-gold',
      yellowStateCompleted: 'bg-white text-google-yellow border-white animate-pulse',
    },
    sidebar: {
      shell: 'border-gray-300 dark:border-gray-700 bg-sidebar-bg flex flex-col shadow-2xl z-40 fixed md:relative right-0 top-[65px] md:top-0 h-[calc(100vh-65px)] md:h-screen transition-all duration-500 ease-[cubic-bezier(0.4,0,0.2,1)] overflow-hidden',
      header: 'p-6 border-b border-google-blue/30 flex items-center justify-between bg-google-blue text-white shadow-lg cursor-pointer hover:bg-google-blue/90 transition-colors group/sidebar-header',
      emptyState: 'flex flex-col items-center justify-center py-20 text-center px-6',
      emptyIcon: 'w-16 h-16 rounded-full bg-gray-100 dark:bg-white/5 flex items-center justify-center text-gray-300 dark:text-gray-700 mb-4',
      emptyText: 'text-[10px] font-heading uppercase text-text-secondary tracking-widest leading-relaxed',
      activeTask: 'group rounded-card border-2 cursor-pointer relative flex flex-col transition-all',
      activeTaskMulti: 'bg-google-red border-google-red text-white shadow-2xl scale-[1.05] z-20 animate-pulse',
      activeTaskFocus: 'bg-google-green border-google-green text-white shadow-lg scale-[1.02] z-10',
      activeTaskYellow: 'bg-google-yellow border-google-yellow text-gray-900 shadow-lg scale-[1.02] z-10',
      inactiveTask: 'bg-google-blue/5 dark:bg-google-blue/10 border-google-blue dark:border-google-blue hover:border-google-blue min-h-[64px]',
      deactivatedCompleted: 'bg-google-green/10 border-google-green/20 text-google-green dark:text-google-green/80 shadow-sm min-h-[64px]',
    },
    checklist: {
      container: 'flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-3 py-2 sm:py-2.5 px-3 sm:px-4 rounded-card group transition-all border shadow-sm hover:shadow-md cursor-pointer relative text-text-primary',
      containerActive: 'bg-gray-100 border-google-green dark:bg-black/60 dark:border-google-green ring-4 ring-google-green/30 shadow-lg',
      containerMulti: 'bg-google-red border-google-red text-white shadow-2xl scale-[1.02] z-20 animate-pulse',
      containerInactive: 'bg-white border-blue-200 hover:bg-blue-50/50 dark:hover:bg-blue-900/10 dark:border-gray-800',
      badge: 'text-[8px] font-heading uppercase px-1.5 py-0.5 rounded-md border transition-all',
      badgeActive: 'bg-google-yellow border-google-yellow text-gray-900 shadow-sm',
      badgeInactive: 'bg-gray-100 dark:bg-white/10 text-text-secondary border-gray-200 dark:border-white/10',
    },
    pomodoro: {
      container: 'flex-1 h-10 flex items-center justify-center px-1.5 py-1 rounded-xl transition-all shadow-sm min-w-0 bg-white/10',
      button: 'w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0 transition-all shadow-sm bg-white/20 border-white/30 text-white',
      buttonYellow: 'bg-black/10 border-black/20 text-gray-900',
    },
  },
  animations: {
    pulseGold: 'animate-pulse-gold',
  }
};
